linters:
  enable:
    - copyloopvar
    - gofmt
    - govet
    - gosec
    - revive
    - unused
  disable-all: false
  disable:
    - exportloopref
  presets:
    - bugs
    - performance
    - unused
  fast: false