name: test-scan-docker-image

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'cmd/**'
      - 'pkg/**'
      - 'internal/**'

env:
  IMAGE_NAME: go-api

jobs:
  build-scan-push:
    uses: angelvargass/reusable-workflows/.github/workflows/reusable-docker-build-scan-push.yaml@v1.0.0
    with:
      registry: docker.io
      image_name: 'test'
      image_tag: ${{ github.event.pull_request.head.sha }}
      dockerfile_path: '.'
      push: 'false'
    secrets:
      docker_username: ${{ vars.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}