name: golangci-lint

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [ master ]

permissions:
    contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: 'v1.64.6'
          args: --timeout 5m