name: goreleaser-and-deploy

on:
  workflow_dispatch:
    inputs:
      trigger-goreleaser:
        description: 'Trigger GoReleaser build'
        required: true
        type: boolean
        default: true
      
      trigger-docker-build-scan-release:
        description: 'Trigger Docker build, scan, and release'
        required: true
        type: boolean
        default: true
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    if: ${{ github.event.inputs.trigger-goreleaser == 'true' }} || github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: 1.24
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
  
  build-scan-push:
    if: ${{ github.event.inputs.trigger-docker-build-scan-release == 'true' }} || github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: angelvargass/reusable-workflows/.github/workflows/reusable-docker-build-scan-push.yaml@v1.1.4
    with:
      registry: docker.io
      image_name: 'go-api'
      image_tag: ${{ github.ref_name }}
      dockerfile_path: '.'
    secrets:
      docker_username: ${{ vars.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}